/**
 * Which module each file in src/actions belongs to — so that a workspace whose plan does not include
 * a module cannot reach that module's actions, whatever its pages happen to show.
 *
 * Every exported function of a file mapped to modules must call `requireModuleUser` with one of
 * them (src/lib/modules-access.ts), directly or through a local helper; `check:module-guards`
 * enforces it, and refuses an action file that is not listed here at all. The other answers:
 *
 *   · "core"      — the app itself: signing in, people and roles, settings, companies and leads,
 *                   search, the dashboard. In every plan, so nothing to check.
 *   · "public"    — served to somebody with no account here (a form, the portal, the visitor
 *                   tablet). There is no user to require; each checks `moduleAvailableForTenant`.
 *   · "platform"  — the platform's own (signup, the staff console, the public website and its CMS,
 *                   the partner portal). No workspace plan applies.
 *
 * A file listing several modules serves each of them (a trade document is a sales or a purchase
 * one): its actions are open while any of them is in the plan.
 */

export type ActionScope = "core" | "public" | "platform" | readonly string[];

export const ACTION_MODULES: Record<string, ActionScope> = {
  "access-control.ts": "core",
  "access-gate.ts": "core",
  "access-lock.ts": "core",
  "access.ts": "core",
  // Revenue & Close: prepaids and accruals (src/lib/close/schedules.ts).
  "accounting-schedules.ts": ["revenue_close"],
  "activity-awards.ts": ["wins"],
  "activity-tracking.ts": "core",
  "activity.ts": "core",
  "addon-proposal.ts": ["renewals"],
  "addon.ts": ["renewals"],
  "analytics.ts": ["reports"],
  "asset.ts": ["accounting"],
  "attendance.ts": ["hr"],
  "auth.ts": "core",
  "backup.ts": "core",
  "billing.ts": "core",
  "bank.ts": ["accounting"],
  "biometric.ts": ["hr"],
  "books.ts": ["accounting"],
  "brand.ts": ["items"],
  "branding.ts": "core",
  "call.ts": ["calls"],
  "calling-activity.ts": ["calls"],
  "candidate.ts": ["hr"],
  "celebration.ts": ["hr"],
  // Revenue & Close: the month-end checklist, closing a month, flux and the close settings (src/lib/close).
  "close.ts": ["revenue_close"],
  // Collections: a salesperson's dues and payment follow-ups — Receivables' (src/lib/collections).
  "collections.ts": ["receivables"],
  "commission-party.ts": ["commission_parties"],
  "company-location.ts": "core",
  "company-merge.ts": "core",
  "company.ts": "core",
  "consignment.ts": ["it_assets"],
  "contact.ts": "core",
  "copilot.ts": "core",
  "credit.ts": ["receivables"],
  "customer-category.ts": "core",
  "dashboard.ts": "core",
  "data-export.ts": "core",
  "data-import.ts": "core",
  "data-reset.ts": "core",
  "department.ts": "core",
  "dlp.ts": "core",
  "document-approval.ts": ["sales_documents", "purchase_documents"],
  "document-mail.ts": ["sales_documents", "purchase_documents"],
  "document-number.ts": ["sales_documents", "purchase_documents"],
  "domain.ts": ["domains"],
  // Settings › Domain: the workspace's own addresses (custom domains) — the owner's, like billing; not the Domains module above.
  "domains.ts": "core",
  // Checking a contact's address belongs to having contacts, which every plan has; the Contact Checks
  // page that lists the failures is the Workspace module's.
  "email-verification.ts": "core",
  "exchange-rate.ts": "core",
  "employee-docs.ts": ["hr"],
  "eway.ts": ["sales_documents"],
  "expense.ts": ["expenses"],
  "feedback-public.ts": "public",
  "feedback.ts": ["feedback"],
  "finance.ts": ["accounting"],
  "forecast.ts": ["forecast"],
  "forms.ts": ["forms"],
  "geo.ts": "core",
  "handover.ts": "core",
  "help.ts": "core",
  "hr.ts": ["hr"],
  "impersonation.ts": "core",
  "incentive.ts": ["incentives"],
  "industry.ts": "core",
  "intake.ts": "public",
  "internal-feedback.ts": ["engagement"],
  "it-asset.ts": ["it_assets"],
  "item.ts": ["items"],
  "lead-assignment.ts": "core",
  "lead-capture.ts": "core",
  "lead.ts": "core",
  "leave.ts": ["hr"],
  "ledger-reports.ts": ["accounting"],
  "ledger.ts": ["accounting"],
  // Linked sign-in: a person's own accounts in other workspaces, and the Security card's rule — every plan (owner decision 10).
  "linked-sign-in.ts": "core",
  "linked-sign-in-admin.ts": "core",
  "mail-log.ts": "core",
  "maintenance.ts": "core",
  "marketing-public.ts": "public",
  "marketing.ts": ["marketing"],
  "messaging-provider.ts": ["marketing"],
  "module.ts": "core",
  "note.ts": ["notes"],
  "notification.ts": ["notifications"],
  "order-notice.ts": ["orders", "renewals"],
  "order.ts": ["orders"],
  // Backend rebates on orders, their programmes and the report (owner, 1 Oct 2026).
  "rebate.ts": ["orders"],
  // Branches and GST registrations are the company itself, not a module: every document names one.
  "branch.ts": "core",
  // Getting started: the onboarding wizard's steps, skips and completion (src/lib/help).
  "onboarding.ts": "core",
  "organisation.ts": "core",
  "page-layout.ts": "core",
  "password-reset.ts": "public",
  "payable.ts": ["payables"],
  // What distributors and OEMs give back — set against bills and orders' rebates.
  "vendor-credit.ts": ["payables"],
  "payment.ts": ["payments"],
  "payroll.ts": ["payroll"],
  "performance.ts": "core",
  "permission.ts": "core",
  "portal-public.ts": "public",
  "portal.ts": ["customer_portal"],
  "prizes.ts": ["wins"],
  "profile.ts": "core",
  "project-credential.ts": ["projects"],
  "project-document.ts": ["projects"],
  "project.ts": ["projects"],
  "receivable.ts": ["receivables"],
  "reconcile.ts": ["purchase_documents"],
  "reference-data.ts": "core",
  "regularisation.ts": ["hr"],
  "renewal-order.ts": ["renewals"],
  "renewal-proposal.ts": ["renewals"],
  "renewal-stage.ts": ["renewals"],
  "renewal.ts": ["renewals"],
  "reseller.ts": ["resellers"],
  // Revenue & Close: revenue recognition — schedules, the run, the opening wizard (src/lib/revenue).
  "revenue.ts": ["revenue_close"],
  // Revenue & Close: what the revenue screens read beside it, and the waterfall's CSV.
  "revenue-screens.ts": ["revenue_close"],
  "role.ts": "core",
  "search.ts": "core",
  "security-policy.ts": "core",
  "security.ts": "core",
  "settlement.ts": ["payroll"],
  "support-access.ts": "core",
  // Contact Support: asking the platform for help is part of every plan.
  "support.ts": "core",
  "support-load.ts": ["helpdesk"],
  "survey.ts": ["engagement"],
  "table-preference.ts": "core",
  "target.ts": ["targets"],
  "task.ts": ["tasks"],
  "tax-reports.ts": ["accounting"],
  "ticket.ts": ["helpdesk"],
  "trade-document.ts": ["sales_documents", "purchase_documents"],
  "transporter.ts": ["sales_documents", "it_assets"],
  "user-photo.ts": "core",
  "user.ts": "core",
  "vault.ts": ["vault"],
  "verification.ts": ["workspace"],
  "view-mode.ts": "core",
  "visit.ts": ["visits"],
  "visitor-public.ts": "public",
  "visitor.ts": ["visitors"],
  "wins.ts": ["wins"],
  "workspace.ts": ["workspace"],
  "platform/console-admin.ts": "platform",
  "platform/console-alerts.ts": "platform",
  "platform/console-announcements.ts": "platform",
  "platform/console-billing.ts": "platform",
  "platform/console-commissions.ts": "platform",
  "platform/console-directory.ts": "platform",
  "platform/console-domains.ts": "platform",
  "platform/console-linked.ts": "platform",
  "platform/console-names.ts": "platform",
  "platform/console-partners.ts": "platform",
  "platform/console-shell.ts": "platform",
  "platform/console-support.ts": "platform",
  "platform/console-website.ts": "platform",
  "platform/console-workspace.ts": "platform",
  "platform/console.ts": "platform",
  "platform/partner-site.ts": "platform",
  "platform/signup.ts": "platform",
  "platform/site.ts": "platform",
  "platform/staff-auth.ts": "platform",
  // The website CMS (cms.<domain>): its own accounts, and only the control plane's site tables.
  "cms/auth.ts": "platform",
  "cms/categories.ts": "platform",
  "cms/leads.ts": "platform",
  "cms/media.ts": "platform",
  "cms/pages.ts": "platform",
  "cms/posts.ts": "platform",
  "cms/redirects.ts": "platform",
  "cms/seo.ts": "platform",
  "cms/settings.ts": "platform",
  "cms/tags.ts": "platform",
  "cms/users.ts": "platform",
  // The partner portal (partners.<domain>): its own accounts, and only the control plane's partner tables.
  "partners/auth.ts": "platform",
  "partners/commissions.ts": "platform",
  "partners/deals.ts": "platform",
  "partners/invitations.ts": "platform",
  "partners/profile.ts": "platform",
  "partners/resellers.ts": "platform",
  "partners/team.ts": "platform",
};

/**
 * Public actions that work whatever the plan, each for a stated reason. Every other export of a
 * "public" file checks `moduleAvailableForTenant` first.
 */
export const ALWAYS_OPEN: Record<string, string> = {
  "marketing-public.ts:getPreferences": "somebody can always see what they are sent — the law requires it",
  "marketing-public.ts:updatePreferences": "and always change it",
  "marketing-public.ts:unsubscribeAll": "and always stop it",
  "password-reset.ts:requestPasswordReset": "signing in belongs to every plan",
  "password-reset.ts:resetPassword": "signing in belongs to every plan",
  "password-reset.ts:setPasswordAndSignIn": "signing in belongs to every plan",
};
