/**
 * Which module each file in src/actions belongs to — so that a workspace whose plan does not include
 * a module cannot reach that module's actions, whatever its pages happen to show.
 *
 * Every exported function of a file mapped to modules must call `requireModuleUser` with one of
 * them (src/lib/modules-access.ts), directly or through a local helper; `check:module-guards`
 * enforces it, and refuses an action file that is not listed here at all. The other answers:
 *
 *   · "core"      — the app itself: signing in, people and roles, settings, companies and leads,
 *                   search, the dashboard. In every plan, so nothing to check.
 *   · "public"    — served to somebody with no account here (a form, the portal, the visitor
 *                   tablet). There is no user to require; each checks `moduleAvailableForTenant`.
 *   · "platform"  — the platform's own (signup, the staff console). No workspace plan applies.
 *
 * A file listing several modules serves each of them (a trade document is a sales or a purchase
 * one): its actions are open while any of them is in the plan.
 */

export type ActionScope = "core" | "public" | "platform" | readonly string[];

export const ACTION_MODULES: Record<string, ActionScope> = {
  "access-control.ts": "core",
  "access-gate.ts": "core",
  "access-lock.ts": "core",
  "access.ts": "core",
  "activity-awards.ts": ["wins"],
  "activity-tracking.ts": "core",
  "activity.ts": "core",
  "addon-proposal.ts": ["renewals"],
  "addon.ts": ["renewals"],
  "analytics.ts": ["reports"],
  "asset.ts": ["accounting"],
  "attendance.ts": ["hr"],
  "auth.ts": "core",
  "backup.ts": "core",
  "billing.ts": "core",
  "bank.ts": ["accounting"],
  "biometric.ts": ["hr"],
  "books.ts": ["accounting"],
  "brand.ts": ["items"],
  "branding.ts": "core",
  "call.ts": ["calls"],
  "calling-activity.ts": ["calls"],
  "candidate.ts": ["hr"],
  "celebration.ts": ["hr"],
  "commission-party.ts": ["commission_parties"],
  "company-location.ts": "core",
  "company-merge.ts": "core",
  "company.ts": "core",
  "consignment.ts": ["it_assets"],
  "contact.ts": "core",
  "copilot.ts": "core",
  "credit.ts": ["receivables"],
  "customer-category.ts": "core",
  "dashboard.ts": "core",
  "data-export.ts": "core",
  "data-import.ts": "core",
  "data-reset.ts": "core",
  "department.ts": "core",
  "dlp.ts": "core",
  "document-approval.ts": ["sales_documents", "purchase_documents"],
  "document-mail.ts": ["sales_documents", "purchase_documents"],
  "document-number.ts": ["sales_documents", "purchase_documents"],
  "domain.ts": ["domains"],
  // Checking a contact's address belongs to having contacts, which every plan has; the Contact Checks
  // page that lists the failures is the Workspace module's.
  "email-verification.ts": "core",
  "exchange-rate.ts": "core",
  "employee-docs.ts": ["hr"],
  "eway.ts": ["sales_documents"],
  "expense.ts": ["expenses"],
  "feedback-public.ts": "public",
  "feedback.ts": ["feedback"],
  "finance.ts": ["accounting"],
  "forecast.ts": ["forecast"],
  "forms.ts": ["forms"],
  "geo.ts": "core",
  "handover.ts": "core",
  "help.ts": "core",
  "hr.ts": ["hr"],
  "impersonation.ts": "core",
  "incentive.ts": ["incentives"],
  "industry.ts": "core",
  "intake.ts": "public",
  "internal-feedback.ts": ["engagement"],
  "it-asset.ts": ["it_assets"],
  "item.ts": ["items"],
  "lead-assignment.ts": "core",
  "lead-capture.ts": "core",
  "lead.ts": "core",
  "leave.ts": ["hr"],
  "ledger-reports.ts": ["accounting"],
  "ledger.ts": ["accounting"],
  "mail-log.ts": "core",
  "maintenance.ts": "core",
  "marketing-public.ts": "public",
  "marketing.ts": ["marketing"],
  "messaging-provider.ts": ["marketing"],
  "module.ts": "core",
  "note.ts": ["notes"],
  "notification.ts": ["notifications"],
  "order-notice.ts": ["orders", "renewals"],
  "order.ts": ["orders"],
  "organisation.ts": "core",
  "page-layout.ts": "core",
  "password-reset.ts": "public",
  "payable.ts": ["payables"],
  "payment.ts": ["payments"],
  "payroll.ts": ["payroll"],
  "performance.ts": "core",
  "permission.ts": "core",
  "portal-public.ts": "public",
  "portal.ts": ["customer_portal"],
  "prizes.ts": ["wins"],
  "profile.ts": "core",
  "project-credential.ts": ["projects"],
  "project-document.ts": ["projects"],
  "project.ts": ["projects"],
  "receivable.ts": ["receivables"],
  "reconcile.ts": ["purchase_documents"],
  "reference-data.ts": "core",
  "regularisation.ts": ["hr"],
  "renewal-order.ts": ["renewals"],
  "renewal-proposal.ts": ["renewals"],
  "renewal-stage.ts": ["renewals"],
  "renewal.ts": ["renewals"],
  "reseller.ts": ["resellers"],
  "role.ts": "core",
  "search.ts": "core",
  "security-policy.ts": "core",
  "security.ts": "core",
  "settlement.ts": ["payroll"],
  "support-access.ts": "core",
  "support-load.ts": ["helpdesk"],
  "survey.ts": ["engagement"],
  "table-preference.ts": "core",
  "target.ts": ["targets"],
  "task.ts": ["tasks"],
  "tax-reports.ts": ["accounting"],
  "ticket.ts": ["helpdesk"],
  "trade-document.ts": ["sales_documents", "purchase_documents"],
  "transporter.ts": ["sales_documents", "it_assets"],
  "user-photo.ts": "core",
  "user.ts": "core",
  "vault.ts": ["vault"],
  "verification.ts": ["workspace"],
  "view-mode.ts": "core",
  "visit.ts": ["visits"],
  "visitor-public.ts": "public",
  "visitor.ts": ["visitors"],
  "wins.ts": ["wins"],
  "workspace.ts": ["workspace"],
  "platform/console.ts": "platform",
  "platform/signup.ts": "platform",
  "platform/staff-auth.ts": "platform",
};

/**
 * Public actions that work whatever the plan, each for a stated reason. Every other export of a
 * "public" file checks `moduleAvailableForTenant` first.
 */
export const ALWAYS_OPEN: Record<string, string> = {
  "marketing-public.ts:getPreferences": "somebody can always see what they are sent — the law requires it",
  "marketing-public.ts:updatePreferences": "and always change it",
  "marketing-public.ts:unsubscribeAll": "and always stop it",
  "password-reset.ts:requestPasswordReset": "signing in belongs to every plan",
  "password-reset.ts:resetPassword": "signing in belongs to every plan",
};
