/**
 * Every country, generated from GeoNames' countryInfo.txt by prisma/reference/geonames-countries.ts
 * — do not edit by hand; regenerate, review the diff, and commit.
 *
 * Country data from GeoNames (geonames.org), CC BY 4.0. Names the app already stored are kept as
 * they were; see the generator for why.
 */
export type WorldCountry = {
  code: string;
  name: string;
  /** GeoNames' pattern for the country's postal codes — a hint for the form, never a refusal. */
  postalRegex?: string;
  /** "#" a digit, "@" a letter: "@# #@@|@## #@@". */
  postalFormat?: string;
  phone?: string;
  currency?: string;
};

export const WORLD_COUNTRIES: WorldCountry[] = [
  { code: "IN", name: "India", postalRegex: "^(\\d{6})$", postalFormat: "######", phone: "91", currency: "INR" },
  { code: "AF", name: "Afghanistan", phone: "93", currency: "AFN" },
  { code: "AX", name: "Aland Islands", postalRegex: "^(?:FI)*(\\d{5})$", postalFormat: "#####", phone: "+358-18", currency: "EUR" },
  { code: "AL", name: "Albania", postalRegex: "^(\\d{4})$", postalFormat: "####", phone: "355", currency: "ALL" },
  { code: "DZ", name: "Algeria", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "213", currency: "DZD" },
  { code: "AS", name: "American Samoa", postalRegex: "96799", postalFormat: "#####-####", phone: "+1-684", currency: "USD" },
  { code: "AD", name: "Andorra", postalRegex: "^(?:AD)*(\\d{3})$", postalFormat: "AD###", phone: "376", currency: "EUR" },
  { code: "AO", name: "Angola", phone: "244", currency: "AOA" },
  { code: "AI", name: "Anguilla", postalRegex: "^(?:AZ)*(\\d{4})$", postalFormat: "AI-####", phone: "+1-264", currency: "XCD" },
  { code: "AQ", name: "Antarctica" },
  { code: "AG", name: "Antigua and Barbuda", phone: "+1-268", currency: "XCD" },
  { code: "AR", name: "Argentina", postalRegex: "^[A-Z]?\\d{4}[A-Z]{0,3}$", postalFormat: "@####@@@", phone: "54", currency: "ARS" },
  { code: "AM", name: "Armenia", postalRegex: "^(\\d{6})$", postalFormat: "######", phone: "374", currency: "AMD" },
  { code: "AW", name: "Aruba", phone: "297", currency: "AWG" },
  { code: "AU", name: "Australia", postalRegex: "^(\\d{4})$", postalFormat: "####", phone: "61", currency: "AUD" },
  { code: "AT", name: "Austria", postalRegex: "^(\\d{4})$", postalFormat: "####", phone: "43", currency: "EUR" },
  { code: "AZ", name: "Azerbaijan", postalRegex: "^(?:AZ )*(\\d{4})$", postalFormat: "AZ ####", phone: "994", currency: "AZN" },
  { code: "BS", name: "Bahamas", phone: "+1-242", currency: "BSD" },
  { code: "BH", name: "Bahrain", postalRegex: "^(\\d{3}\\d?)$", postalFormat: "####|###", phone: "973", currency: "BHD" },
  { code: "BD", name: "Bangladesh", postalRegex: "^(\\d{4})$", postalFormat: "####", phone: "880", currency: "BDT" },
  { code: "BB", name: "Barbados", postalRegex: "^(?:BB)*(\\d{5})$", postalFormat: "BB#####", phone: "+1-246", currency: "BBD" },
  { code: "BY", name: "Belarus", postalRegex: "^(\\d{6})$", postalFormat: "######", phone: "375", currency: "BYN" },
  { code: "BE", name: "Belgium", postalRegex: "^(\\d{4})$", postalFormat: "####", phone: "32", currency: "EUR" },
  { code: "BZ", name: "Belize", phone: "501", currency: "BZD" },
  { code: "BJ", name: "Benin", phone: "229", currency: "XOF" },
  { code: "BM", name: "Bermuda", postalRegex: "^([A-Z]{2}\\d{2})$", postalFormat: "@@ ##", phone: "+1-441", currency: "BMD" },
  { code: "BT", name: "Bhutan", phone: "975", currency: "BTN" },
  { code: "BO", name: "Bolivia", phone: "591", currency: "BOB" },
  { code: "BQ", name: "Bonaire, Saint Eustatius and Saba", phone: "599", currency: "USD" },
  { code: "BA", name: "Bosnia and Herzegovina", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "387", currency: "BAM" },
  { code: "BW", name: "Botswana", phone: "267", currency: "BWP" },
  { code: "BV", name: "Bouvet Island", currency: "NOK" },
  { code: "BR", name: "Brazil", postalRegex: "^\\d{5}-\\d{3}$", postalFormat: "#####-###", phone: "55", currency: "BRL" },
  { code: "IO", name: "British Indian Ocean Territory", postalRegex: "BBND 1ZZ", postalFormat: "BBND 1ZZ", phone: "246", currency: "USD" },
  { code: "VG", name: "British Virgin Islands", phone: "+1-284", currency: "USD" },
  { code: "BN", name: "Brunei", postalRegex: "^([A-Z]{2}\\d{4})$", postalFormat: "@@####", phone: "673", currency: "BND" },
  { code: "BG", name: "Bulgaria", postalRegex: "^(\\d{4})$", postalFormat: "####", phone: "359", currency: "BGN" },
  { code: "BF", name: "Burkina Faso", phone: "226", currency: "XOF" },
  { code: "BI", name: "Burundi", phone: "257", currency: "BIF" },
  { code: "CV", name: "Cabo Verde", postalRegex: "^(\\d{4})$", postalFormat: "####", phone: "238", currency: "CVE" },
  { code: "KH", name: "Cambodia", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "855", currency: "KHR" },
  { code: "CM", name: "Cameroon", phone: "237", currency: "XAF" },
  { code: "CA", name: "Canada", postalRegex: "^([ABCEGHJKLMNPRSTVXY]\\d[ABCEGHJKLMNPRSTVWXYZ]) ?(\\d[ABCEGHJKLMNPRSTVWXYZ]\\d)$", postalFormat: "@#@ #@#", phone: "1", currency: "CAD" },
  { code: "KY", name: "Cayman Islands", phone: "+1-345", currency: "KYD" },
  { code: "CF", name: "Central African Republic", phone: "236", currency: "XAF" },
  { code: "TD", name: "Chad", postalRegex: "^(TKCA 1ZZ)$", postalFormat: "TKCA 1ZZ", phone: "235", currency: "XAF" },
  { code: "CL", name: "Chile", postalRegex: "^(\\d{7})$", postalFormat: "#######", phone: "56", currency: "CLP" },
  { code: "CN", name: "China", postalRegex: "^(\\d{6})$", postalFormat: "######", phone: "86", currency: "CNY" },
  { code: "CX", name: "Christmas Island", postalRegex: "^(\\d{4})$", postalFormat: "####", phone: "61", currency: "AUD" },
  { code: "CC", name: "Cocos Islands", postalRegex: "^(\\d{4})$", postalFormat: "####", phone: "61", currency: "AUD" },
  { code: "CO", name: "Colombia", postalRegex: "^(\\d{6})$", postalFormat: "######", phone: "57", currency: "COP" },
  { code: "KM", name: "Comoros", phone: "269", currency: "KMF" },
  { code: "CK", name: "Cook Islands", phone: "682", currency: "NZD" },
  { code: "CR", name: "Costa Rica", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "506", currency: "CRC" },
  { code: "HR", name: "Croatia", postalRegex: "^(?:HR)*(\\d{5})$", postalFormat: "#####", phone: "385", currency: "EUR" },
  { code: "CU", name: "Cuba", postalRegex: "^(?:CP)*(\\d{5})$", postalFormat: "CP #####", phone: "53", currency: "CUP" },
  { code: "CW", name: "Curacao", phone: "599", currency: "XCG" },
  { code: "CY", name: "Cyprus", postalRegex: "^(\\d{4})$", postalFormat: "####", phone: "357", currency: "EUR" },
  { code: "CZ", name: "Czechia", postalRegex: "^\\d{3}\\s?\\d{2}$", postalFormat: "### ##", phone: "420", currency: "CZK" },
  { code: "CD", name: "Democratic Republic of the Congo", phone: "243", currency: "CDF" },
  { code: "DK", name: "Denmark", postalRegex: "^(\\d{4})$", postalFormat: "####", phone: "45", currency: "DKK" },
  { code: "DJ", name: "Djibouti", phone: "253", currency: "DJF" },
  { code: "DM", name: "Dominica", phone: "+1-767", currency: "XCD" },
  { code: "DO", name: "Dominican Republic", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "+1-809 and 1-829", currency: "DOP" },
  { code: "EC", name: "Ecuador", postalRegex: "^([a-zA-Z]\\d{4}[a-zA-Z])$", postalFormat: "@####@", phone: "593", currency: "USD" },
  { code: "EG", name: "Egypt", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "20", currency: "EGP" },
  { code: "SV", name: "El Salvador", postalRegex: "^(?:CP)*(\\d{4})$", postalFormat: "CP ####", phone: "503", currency: "USD" },
  { code: "GQ", name: "Equatorial Guinea", phone: "240", currency: "XAF" },
  { code: "ER", name: "Eritrea", phone: "291", currency: "ERN" },
  { code: "EE", name: "Estonia", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "372", currency: "EUR" },
  { code: "SZ", name: "Eswatini", postalRegex: "^([A-Z]\\d{3})$", postalFormat: "@###", phone: "268", currency: "SZL" },
  { code: "ET", name: "Ethiopia", postalRegex: "^(\\d{4})$", postalFormat: "####", phone: "251", currency: "ETB" },
  { code: "FK", name: "Falkland Islands", postalRegex: "FIQQ 1ZZ", postalFormat: "FIQQ 1ZZ", phone: "500", currency: "FKP" },
  { code: "FO", name: "Faroe Islands", postalRegex: "^(?:FO)*(\\d{3})$", postalFormat: "###", phone: "298", currency: "DKK" },
  { code: "FJ", name: "Fiji", phone: "679", currency: "FJD" },
  { code: "FI", name: "Finland", postalRegex: "^(?:FI)*(\\d{5})$", postalFormat: "#####", phone: "358", currency: "EUR" },
  { code: "FR", name: "France", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "33", currency: "EUR" },
  { code: "GF", name: "French Guiana", postalRegex: "^((97|98)3\\d{2})$", postalFormat: "#####", phone: "594", currency: "EUR" },
  { code: "PF", name: "French Polynesia", postalRegex: "^((97|98)7\\d{2})$", postalFormat: "#####", phone: "689", currency: "XPF" },
  { code: "TF", name: "French Southern Territories", currency: "EUR" },
  { code: "GA", name: "Gabon", phone: "241", currency: "XAF" },
  { code: "GM", name: "Gambia", phone: "220", currency: "GMD" },
  { code: "GE", name: "Georgia", postalRegex: "^(\\d{4})$", postalFormat: "####", phone: "995", currency: "GEL" },
  { code: "DE", name: "Germany", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "49", currency: "EUR" },
  { code: "GH", name: "Ghana", phone: "233", currency: "GHS" },
  { code: "GI", name: "Gibraltar", postalRegex: "GX11 1AA", postalFormat: "GX11 1AA", phone: "350", currency: "GIP" },
  { code: "GR", name: "Greece", postalRegex: "^(\\d{5})$", postalFormat: "### ##", phone: "30", currency: "EUR" },
  { code: "GL", name: "Greenland", postalRegex: "^(\\d{4})$", postalFormat: "####", phone: "299", currency: "DKK" },
  { code: "GD", name: "Grenada", phone: "+1-473", currency: "XCD" },
  { code: "GP", name: "Guadeloupe", postalRegex: "^((97|98)\\d{3})$", postalFormat: "#####", phone: "590", currency: "EUR" },
  { code: "GU", name: "Guam", postalRegex: "^(969\\d{2})$", postalFormat: "969##", phone: "+1-671", currency: "USD" },
  { code: "GT", name: "Guatemala", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "502", currency: "GTQ" },
  { code: "GG", name: "Guernsey", postalRegex: "^((?:(?:[A-PR-UWYZ][A-HK-Y]\\d[ABEHMNPRV-Y0-9]|[A-PR-UWYZ]\\d[A-HJKPS-UW0-9])\\s\\d[ABD-HJLNP-UW-Z]{2})|GIR\\s?0AA)$", postalFormat: "@# #@@|@## #@@|@@# #@@|@@## #@@|@#@ #@@|@@#@ #@@|GIR0AA", phone: "+44-1481", currency: "GBP" },
  { code: "GN", name: "Guinea", phone: "224", currency: "GNF" },
  { code: "GW", name: "Guinea-Bissau", postalRegex: "^(\\d{4})$", postalFormat: "####", phone: "245", currency: "XOF" },
  { code: "GY", name: "Guyana", phone: "592", currency: "GYD" },
  { code: "HT", name: "Haiti", postalRegex: "^(?:HT)*(\\d{4})$", postalFormat: "HT####", phone: "509", currency: "HTG" },
  { code: "HM", name: "Heard Island and McDonald Islands", postalRegex: "^(\\d{4})$", postalFormat: "####", currency: "AUD" },
  { code: "HN", name: "Honduras", postalRegex: "^(\\d{6})$", postalFormat: "#####", phone: "504", currency: "HNL" },
  { code: "HK", name: "Hong Kong", postalRegex: "^(\\d{6})$", postalFormat: "######", phone: "852", currency: "HKD" },
  { code: "HU", name: "Hungary", postalRegex: "^(\\d{4})$", postalFormat: "####", phone: "36", currency: "HUF" },
  { code: "IS", name: "Iceland", postalRegex: "^(\\d{3})$", postalFormat: "###", phone: "354", currency: "ISK" },
  { code: "ID", name: "Indonesia", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "62", currency: "IDR" },
  { code: "IR", name: "Iran", postalRegex: "^(\\d{10})$", postalFormat: "##########", phone: "98", currency: "IRR" },
  { code: "IQ", name: "Iraq", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "964", currency: "IQD" },
  { code: "IE", name: "Ireland", postalRegex: "^(D6W|[AC-FHKNPRTV-Y][0-9]{2})\\s?([AC-FHKNPRTV-Y0-9]{4})", postalFormat: "@@@ @@@@", phone: "353", currency: "EUR" },
  { code: "IM", name: "Isle of Man", postalRegex: "^((?:(?:[A-PR-UWYZ][A-HK-Y]\\d[ABEHMNPRV-Y0-9]|[A-PR-UWYZ]\\d[A-HJKPS-UW0-9])\\s\\d[ABD-HJLNP-UW-Z]{2})|GIR\\s?0AA)$", postalFormat: "@# #@@|@## #@@|@@# #@@|@@## #@@|@#@ #@@|@@#@ #@@|GIR0AA", phone: "+44-1624", currency: "GBP" },
  { code: "IL", name: "Israel", postalRegex: "^(\\d{7}|\\d{5})$", postalFormat: "#######", phone: "972", currency: "ILS" },
  { code: "IT", name: "Italy", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "39", currency: "EUR" },
  { code: "CI", name: "Ivory Coast", phone: "225", currency: "XOF" },
  { code: "JM", name: "Jamaica", phone: "+1-876", currency: "JMD" },
  { code: "JP", name: "Japan", postalRegex: "^\\d{3}-\\d{4}$", postalFormat: "###-####", phone: "81", currency: "JPY" },
  { code: "JE", name: "Jersey", postalRegex: "^((?:(?:[A-PR-UWYZ][A-HK-Y]\\d[ABEHMNPRV-Y0-9]|[A-PR-UWYZ]\\d[A-HJKPS-UW0-9])\\s\\d[ABD-HJLNP-UW-Z]{2})|GIR\\s?0AA)$", postalFormat: "@# #@@|@## #@@|@@# #@@|@@## #@@|@#@ #@@|@@#@ #@@|GIR0AA", phone: "+44-1534", currency: "GBP" },
  { code: "JO", name: "Jordan", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "962", currency: "JOD" },
  { code: "KZ", name: "Kazakhstan", postalRegex: "^(\\d{6})$", postalFormat: "######", phone: "7", currency: "KZT" },
  { code: "KE", name: "Kenya", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "254", currency: "KES" },
  { code: "KI", name: "Kiribati", phone: "686", currency: "AUD" },
  { code: "KW", name: "Kuwait", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "965", currency: "KWD" },
  { code: "KG", name: "Kyrgyzstan", postalRegex: "^(\\d{6})$", postalFormat: "######", phone: "996", currency: "KGS" },
  { code: "LA", name: "Laos", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "856", currency: "LAK" },
  { code: "LV", name: "Latvia", postalRegex: "^(?:LV)*(\\d{4})$", postalFormat: "LV-####", phone: "371", currency: "EUR" },
  { code: "LB", name: "Lebanon", postalRegex: "^(\\d{4}(\\d{4})?)$", postalFormat: "#### ####|####", phone: "961", currency: "LBP" },
  { code: "LS", name: "Lesotho", postalRegex: "^(\\d{3})$", postalFormat: "###", phone: "266", currency: "LSL" },
  { code: "LR", name: "Liberia", postalRegex: "^(\\d{4})$", postalFormat: "####", phone: "231", currency: "LRD" },
  { code: "LY", name: "Libya", phone: "218", currency: "LYD" },
  { code: "LI", name: "Liechtenstein", postalRegex: "^(\\d{4})$", postalFormat: "####", phone: "423", currency: "CHF" },
  { code: "LT", name: "Lithuania", postalRegex: "^(?:LT)*(\\d{5})$", postalFormat: "LT-#####", phone: "370", currency: "EUR" },
  { code: "LU", name: "Luxembourg", postalRegex: "^(?:L-)?\\d{4}$", postalFormat: "L-####", phone: "352", currency: "EUR" },
  { code: "MO", name: "Macao", postalRegex: "^(\\d{6})$", postalFormat: "######", phone: "853", currency: "MOP" },
  { code: "MG", name: "Madagascar", postalRegex: "^(\\d{3})$", postalFormat: "###", phone: "261", currency: "MGA" },
  { code: "MW", name: "Malawi", postalRegex: "^(\\d{6})$", postalFormat: "######", phone: "265", currency: "MWK" },
  { code: "MY", name: "Malaysia", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "60", currency: "MYR" },
  { code: "MV", name: "Maldives", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "960", currency: "MVR" },
  { code: "ML", name: "Mali", phone: "223", currency: "XOF" },
  { code: "MT", name: "Malta", postalRegex: "^[A-Z]{3}\\s?\\d{4}$", postalFormat: "@@@ ####", phone: "356", currency: "EUR" },
  { code: "MH", name: "Marshall Islands", postalRegex: "^969\\d{2}(-\\d{4})$", postalFormat: "#####-####", phone: "692", currency: "USD" },
  { code: "MQ", name: "Martinique", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "596", currency: "EUR" },
  { code: "MR", name: "Mauritania", phone: "222", currency: "MRU" },
  { code: "MU", name: "Mauritius", phone: "230", currency: "MUR" },
  { code: "YT", name: "Mayotte", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "262", currency: "EUR" },
  { code: "MX", name: "Mexico", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "52", currency: "MXN" },
  { code: "FM", name: "Micronesia", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "691", currency: "USD" },
  { code: "MD", name: "Moldova", postalRegex: "^MD-\\d{4}$", postalFormat: "MD-####", phone: "373", currency: "MDL" },
  { code: "MC", name: "Monaco", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "377", currency: "EUR" },
  { code: "MN", name: "Mongolia", postalRegex: "^(\\d{6})$", postalFormat: "######", phone: "976", currency: "MNT" },
  { code: "ME", name: "Montenegro", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "382", currency: "EUR" },
  { code: "MS", name: "Montserrat", phone: "+1-664", currency: "XCD" },
  { code: "MA", name: "Morocco", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "212", currency: "MAD" },
  { code: "MZ", name: "Mozambique", postalRegex: "^(\\d{4})$", postalFormat: "####", phone: "258", currency: "MZN" },
  { code: "MM", name: "Myanmar", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "95", currency: "MMK" },
  { code: "NA", name: "Namibia", phone: "264", currency: "NAD" },
  { code: "NR", name: "Nauru", postalRegex: "NRU68", postalFormat: "NRU68", phone: "674", currency: "AUD" },
  { code: "NP", name: "Nepal", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "977", currency: "NPR" },
  { code: "NL", name: "Netherlands", postalRegex: "^(\\d{4}\\s?[a-zA-Z]{2})$", postalFormat: "#### @@", phone: "31", currency: "EUR" },
  { code: "NC", name: "New Caledonia", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "687", currency: "XPF" },
  { code: "NZ", name: "New Zealand", postalRegex: "^(\\d{4})$", postalFormat: "####", phone: "64", currency: "NZD" },
  { code: "NI", name: "Nicaragua", postalRegex: "^(\\d{7})$", postalFormat: "###-###-#", phone: "505", currency: "NIO" },
  { code: "NE", name: "Niger", postalRegex: "^(\\d{4})$", postalFormat: "####", phone: "227", currency: "XOF" },
  { code: "NG", name: "Nigeria", postalRegex: "^(\\d{6})$", postalFormat: "######", phone: "234", currency: "NGN" },
  { code: "NU", name: "Niue", postalRegex: "^(\\d{4})$", postalFormat: "####", phone: "683", currency: "NZD" },
  { code: "NF", name: "Norfolk Island", postalRegex: "^(\\d{4})$", postalFormat: "####", phone: "672", currency: "AUD" },
  { code: "KP", name: "North Korea", postalRegex: "^(\\d{6})$", postalFormat: "###-###", phone: "850", currency: "KPW" },
  { code: "MK", name: "North Macedonia", postalRegex: "^(\\d{4})$", postalFormat: "####", phone: "389", currency: "MKD" },
  { code: "MP", name: "Northern Mariana Islands", postalRegex: "^9695\\d{1}$", postalFormat: "#####", phone: "+1-670", currency: "USD" },
  { code: "NO", name: "Norway", postalRegex: "^(\\d{4})$", postalFormat: "####", phone: "47", currency: "NOK" },
  { code: "OM", name: "Oman", postalRegex: "^(\\d{3})$", postalFormat: "###", phone: "968", currency: "OMR" },
  { code: "PK", name: "Pakistan", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "92", currency: "PKR" },
  { code: "PW", name: "Palau", postalRegex: "^(96940)$", postalFormat: "96940", phone: "680", currency: "USD" },
  { code: "PS", name: "Palestinian Territory", phone: "970", currency: "ILS" },
  { code: "PA", name: "Panama", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "507", currency: "PAB" },
  { code: "PG", name: "Papua New Guinea", postalRegex: "^(\\d{3})$", postalFormat: "###", phone: "675", currency: "PGK" },
  { code: "PY", name: "Paraguay", postalRegex: "^(\\d{4})$", postalFormat: "####", phone: "595", currency: "PYG" },
  { code: "PE", name: "Peru", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "51", currency: "PEN" },
  { code: "PH", name: "Philippines", postalRegex: "^(\\d{4})$", postalFormat: "####", phone: "63", currency: "PHP" },
  { code: "PN", name: "Pitcairn", postalRegex: "PCRN 1ZZ", postalFormat: "PCRN 1ZZ", phone: "870", currency: "NZD" },
  { code: "PL", name: "Poland", postalRegex: "^\\d{2}-\\d{3}$", postalFormat: "##-###", phone: "48", currency: "PLN" },
  { code: "PT", name: "Portugal", postalRegex: "^\\d{4}-\\d{3}\\s?[a-zA-Z]{0,25}$", postalFormat: "####-###", phone: "351", currency: "EUR" },
  { code: "PR", name: "Puerto Rico", postalRegex: "^00[679]\\d{2}(?:-\\d{4})?$", postalFormat: "#####-####", phone: "+1-787 and 1-939", currency: "USD" },
  { code: "QA", name: "Qatar", phone: "974", currency: "QAR" },
  { code: "CG", name: "Republic of the Congo", phone: "242", currency: "XAF" },
  { code: "RE", name: "Reunion", postalRegex: "^((97|98)(4|7|8)\\d{2})$", postalFormat: "#####", phone: "262", currency: "EUR" },
  { code: "RO", name: "Romania", postalRegex: "^(\\d{6})$", postalFormat: "######", phone: "40", currency: "RON" },
  { code: "RU", name: "Russia", postalRegex: "^(\\d{6})$", postalFormat: "######", phone: "7", currency: "RUB" },
  { code: "RW", name: "Rwanda", phone: "250", currency: "RWF" },
  { code: "BL", name: "Saint Barthelemy", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "590", currency: "EUR" },
  { code: "SH", name: "Saint Helena", postalRegex: "^(STHL1ZZ)$", postalFormat: "STHL 1ZZ", phone: "290", currency: "SHP" },
  { code: "KN", name: "Saint Kitts and Nevis", phone: "+1-869", currency: "XCD" },
  { code: "LC", name: "Saint Lucia", phone: "+1-758", currency: "XCD" },
  { code: "MF", name: "Saint Martin", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "590", currency: "EUR" },
  { code: "PM", name: "Saint Pierre and Miquelon", postalRegex: "^(97500)$", postalFormat: "#####", phone: "508", currency: "EUR" },
  { code: "VC", name: "Saint Vincent and the Grenadines", phone: "+1-784", currency: "XCD" },
  { code: "WS", name: "Samoa", postalRegex: "AS 96799", postalFormat: "AS 96799", phone: "685", currency: "WST" },
  { code: "SM", name: "San Marino", postalRegex: "^(4789\\d)$", postalFormat: "4789#", phone: "378", currency: "EUR" },
  { code: "ST", name: "Sao Tome and Principe", phone: "239", currency: "STN" },
  { code: "SA", name: "Saudi Arabia", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "966", currency: "SAR" },
  { code: "SN", name: "Senegal", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "221", currency: "XOF" },
  { code: "RS", name: "Serbia", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "381", currency: "RSD" },
  { code: "SC", name: "Seychelles", phone: "248", currency: "SCR" },
  { code: "SL", name: "Sierra Leone", phone: "232", currency: "SLE" },
  { code: "SG", name: "Singapore", postalRegex: "^(\\d{6})$", postalFormat: "######", phone: "65", currency: "SGD" },
  { code: "SX", name: "Sint Maarten", phone: "599", currency: "XCG" },
  { code: "SK", name: "Slovakia", postalRegex: "^\\d{3}\\s?\\d{2}$", postalFormat: "### ##", phone: "421", currency: "EUR" },
  { code: "SI", name: "Slovenia", postalRegex: "^(?:SI)*(\\d{4})$", postalFormat: "####", phone: "386", currency: "EUR" },
  { code: "SB", name: "Solomon Islands", phone: "677", currency: "SBD" },
  { code: "SO", name: "Somalia", postalRegex: "^([A-Z]{2}\\d{5})$", postalFormat: "@@  #####", phone: "252", currency: "SOS" },
  { code: "ZA", name: "South Africa", postalRegex: "^(\\d{4})$", postalFormat: "####", phone: "27", currency: "ZAR" },
  { code: "GS", name: "South Georgia and the South Sandwich Islands", postalRegex: "SIQQ 1ZZ", postalFormat: "SIQQ 1ZZ", currency: "GBP" },
  { code: "KR", name: "South Korea", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "82", currency: "KRW" },
  { code: "SS", name: "South Sudan", phone: "211", currency: "SSP" },
  { code: "ES", name: "Spain", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "34", currency: "EUR" },
  { code: "LK", name: "Sri Lanka", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "94", currency: "LKR" },
  { code: "SD", name: "Sudan", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "249", currency: "SDG" },
  { code: "SR", name: "Suriname", phone: "597", currency: "SRD" },
  { code: "SJ", name: "Svalbard and Jan Mayen", postalRegex: "^(\\d{4})$", postalFormat: "####", phone: "47", currency: "NOK" },
  { code: "SE", name: "Sweden", postalRegex: "^(?:SE)?\\d{3}\\s\\d{2}$", postalFormat: "### ##", phone: "46", currency: "SEK" },
  { code: "CH", name: "Switzerland", postalRegex: "^(\\d{4})$", postalFormat: "####", phone: "41", currency: "CHF" },
  { code: "SY", name: "Syria", phone: "963", currency: "SYP" },
  { code: "TW", name: "Taiwan", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "886", currency: "TWD" },
  { code: "TJ", name: "Tajikistan", postalRegex: "^(\\d{6})$", postalFormat: "######", phone: "992", currency: "TJS" },
  { code: "TZ", name: "Tanzania", phone: "255", currency: "TZS" },
  { code: "TH", name: "Thailand", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "66", currency: "THB" },
  { code: "TL", name: "Timor Leste", phone: "670", currency: "USD" },
  { code: "TG", name: "Togo", phone: "228", currency: "XOF" },
  { code: "TK", name: "Tokelau", phone: "690", currency: "NZD" },
  { code: "TO", name: "Tonga", phone: "676", currency: "TOP" },
  { code: "TT", name: "Trinidad and Tobago", phone: "+1-868", currency: "TTD" },
  { code: "TN", name: "Tunisia", postalRegex: "^(\\d{4})$", postalFormat: "####", phone: "216", currency: "TND" },
  { code: "TR", name: "Turkey", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "90", currency: "TRY" },
  { code: "TM", name: "Turkmenistan", postalRegex: "^(\\d{6})$", postalFormat: "######", phone: "993", currency: "TMT" },
  { code: "TC", name: "Turks and Caicos Islands", postalRegex: "^(TKCA 1ZZ)$", postalFormat: "TKCA 1ZZ", phone: "+1-649", currency: "USD" },
  { code: "TV", name: "Tuvalu", phone: "688", currency: "AUD" },
  { code: "VI", name: "U.S. Virgin Islands", postalRegex: "^008\\d{2}(?:-\\d{4})?$", postalFormat: "#####-####", phone: "+1-340", currency: "USD" },
  { code: "UG", name: "Uganda", phone: "256", currency: "UGX" },
  { code: "UA", name: "Ukraine", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "380", currency: "UAH" },
  { code: "AE", name: "United Arab Emirates", postalRegex: "^\\d{5}-\\d{5}$", postalFormat: "##### #####", phone: "971", currency: "AED" },
  { code: "GB", name: "United Kingdom", postalRegex: "^([Gg][Ii][Rr]\\s?0[Aa]{2})|((([A-Za-z][0-9]{1,2})|(([A-Za-z][A-Ha-hJ-Yj-y][0-9]{1,2})|(([A-Za-z][0-9][A-Za-z])|([A-Za-z][A-Ha-hJ-Yj-y][0-9]?[A-Za-z]))))\\s?[0-9][A-Za-z]{2})$", postalFormat: "@# #@@|@## #@@|@@# #@@|@@## #@@|@#@ #@@|@@#@ #@@|GIR0AA", phone: "44", currency: "GBP" },
  { code: "US", name: "United States", postalRegex: "^\\d{5}(-\\d{4})?$", postalFormat: "#####-####", phone: "1", currency: "USD" },
  { code: "UM", name: "United States Minor Outlying Islands", phone: "1", currency: "USD" },
  { code: "UY", name: "Uruguay", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "598", currency: "UYU" },
  { code: "UZ", name: "Uzbekistan", postalRegex: "^(\\d{6})$", postalFormat: "######", phone: "998", currency: "UZS" },
  { code: "VU", name: "Vanuatu", phone: "678", currency: "VUV" },
  { code: "VA", name: "Vatican", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "379", currency: "EUR" },
  { code: "VE", name: "Venezuela", postalRegex: "^(\\d{4})$", postalFormat: "####", phone: "58", currency: "VES" },
  { code: "VN", name: "Vietnam", postalRegex: "^(\\d{6})$", postalFormat: "######", phone: "84", currency: "VND" },
  { code: "WF", name: "Wallis and Futuna", postalRegex: "^(986\\d{2})$", postalFormat: "#####", phone: "681", currency: "XPF" },
  { code: "EH", name: "Western Sahara", phone: "212", currency: "MAD" },
  { code: "YE", name: "Yemen", phone: "967", currency: "YER" },
  { code: "ZM", name: "Zambia", postalRegex: "^(\\d{5})$", postalFormat: "#####", phone: "260", currency: "ZMW" },
  { code: "ZW", name: "Zimbabwe", phone: "263", currency: "ZWG" },
];
