import {
  Award,
  Ban,
  Banknote,
  Briefcase,
  Building2,
  Cpu,
  Crown,
  Diamond,
  Factory,
  Flag,
  Flame,
  Gem,
  Globe,
  GraduationCap,
  Handshake,
  Heart,
  HeartPulse,
  Hospital,
  Hotel,
  Hourglass,
  Landmark,
  Leaf,
  Lock,
  Medal,
  PiggyBank,
  Rocket,
  Scale,
  School,
  Server,
  ShieldCheck,
  ShoppingCart,
  Snail,
  Sparkles,
  Star,
  Stethoscope,
  Store,
  Tag,
  Target,
  ThumbsUp,
  TrendingUp,
  TriangleAlert,
  Truck,
  University,
  Users,
  Wallet,
  Warehouse,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * The icons a customer category can wear, by the key stored on the row.
 *
 * A fixed set rather than any Lucide name: a stored name that a later Lucide release renames would
 * quietly render nothing, and a list this size is one somebody can actually choose from.
 */
export const CATEGORY_ICONS: Record<string, { Icon: LucideIcon; label: string }> = {
  star: { Icon: Star, label: "Star" },
  crown: { Icon: Crown, label: "Crown" },
  gem: { Icon: Gem, label: "Gem" },
  diamond: { Icon: Diamond, label: "Diamond" },
  award: { Icon: Award, label: "Award" },
  medal: { Icon: Medal, label: "Medal" },
  sparkles: { Icon: Sparkles, label: "Sparkles" },
  "trending-up": { Icon: TrendingUp, label: "Growing" },
  target: { Icon: Target, label: "Target" },
  rocket: { Icon: Rocket, label: "Rocket" },
  building: { Icon: Building2, label: "Building" },
  factory: { Icon: Factory, label: "Factory" },
  warehouse: { Icon: Warehouse, label: "Warehouse" },
  store: { Icon: Store, label: "Shop" },
  cart: { Icon: ShoppingCart, label: "Retail" },
  briefcase: { Icon: Briefcase, label: "Briefcase" },
  landmark: { Icon: Landmark, label: "Government" },
  scale: { Icon: Scale, label: "Legal" },
  "graduation-cap": { Icon: GraduationCap, label: "Education" },
  school: { Icon: School, label: "School" },
  university: { Icon: University, label: "University" },
  hospital: { Icon: Hospital, label: "Hospital" },
  stethoscope: { Icon: Stethoscope, label: "Clinic" },
  "heart-pulse": { Icon: HeartPulse, label: "Health" },
  hotel: { Icon: Hotel, label: "Hospitality" },
  truck: { Icon: Truck, label: "Logistics" },
  cpu: { Icon: Cpu, label: "Technology" },
  server: { Icon: Server, label: "Data centre" },
  wrench: { Icon: Wrench, label: "Services" },
  leaf: { Icon: Leaf, label: "Green" },
  globe: { Icon: Globe, label: "International" },
  handshake: { Icon: Handshake, label: "Partner" },
  users: { Icon: Users, label: "People" },
  heart: { Icon: Heart, label: "Loyal" },
  "thumbs-up": { Icon: ThumbsUp, label: "Happy" },
  banknote: { Icon: Banknote, label: "Money" },
  wallet: { Icon: Wallet, label: "Wallet" },
  "piggy-bank": { Icon: PiggyBank, label: "Budget" },
  zap: { Icon: Zap, label: "Fast" },
  flame: { Icon: Flame, label: "Hot" },
  "shield-check": { Icon: ShieldCheck, label: "Secure" },
  lock: { Icon: Lock, label: "Confidential" },
  flag: { Icon: Flag, label: "Flag" },
  hourglass: { Icon: Hourglass, label: "Waiting" },
  snail: { Icon: Snail, label: "Slow" },
  alert: { Icon: TriangleAlert, label: "Caution" },
  ban: { Icon: Ban, label: "Blocked" },
  tag: { Icon: Tag, label: "Tag" },
};

export const DEFAULT_CATEGORY_ICON = "tag";

/** Colours that read on both the light and the dark theme. */
export const CATEGORY_COLORS = [
  "#f59e0b",
  "#f97316",
  "#dc2626",
  "#e11d48",
  "#db2777",
  "#8b5cf6",
  "#6366f1",
  "#0ea5e9",
  "#14b8a6",
  "#10b981",
  "#65a30d",
  "#64748b",
] as const;

export const DEFAULT_CATEGORY_COLOR = "#64748b";
